export const API_ENDPOINTS = {
    REELS_FETCHER: '/reelsFetcher',
    CREATE_POST: '/addCrinzMemePost',
    BATCH_PROCESSER: '/batchProcesser',
    GET_POST_COMMENTS: '/getPostComments',
    GET_SHARE_CONTENT: '/getShareContent',
    FETCH_USER_POSTS_AND_REELS: '/fetchUserPostsAndReels',
    GET_USER_DETAILS: '/getUserDetails',
    FETCH_USER_POSTS: '/fetchUserPosts',
    PERSONALIZATION: '/personalization',
    FOLLOW_QUERY_HANDLER: '/follow_query_handler',
    FOLLOW_HANDLER: '/follow_handler',
    HANDLE_EDIT_DELETE_USER_POSTS: '/handleEditDeleteUserPosts',
    POST_CRINZ: '/postCrinz',
    DELETE_USER_ACCOUNT: '/deleteUserAccount',
    GET_CRINZ: '/getCrinz',
    GET_CRINZ_MESSAGES: '/getCrinzMessages',
    REEL_CONTENT_UPLOADER: '/reelContentUploader',
    POST_USER_DATA: '/postUserData',
} as const;
